[package]
version = "0.2.0"
title = "Omniverse Ops Starter"
description = "A data-driven Omniverse Kit extension for creating a compact factory digital twin scene."
category = "Examples"
authors = ["Junbin Kuo"]
keywords = ["omniverse", "openusd", "digital twin", "starter"]

[dependencies]
"omni.ui" = {}
"omni.usd" = {}
"omni.kit.viewport.utility" = {}

[[python.module]]
name = "omniverse.ops.starter"
